

on:
  push:
    branches:
    - '*'

jobs:

  build_on_windows:
  
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements and installer
        run: |
          pip install flet requests multitasking retry psutil pyinstaller httpx nuitka
      - name: Run Nuitka
        run: |
          nuitka main.py --standone --onefile --assume-yes-for-downloads --follow-stdlib --show-scons --show-progress --show-memory --include-data-dir='/Config=Config' --include-data-dir='/lib=lib' --include-data-dir='/ui=ui' --include-data-dir='/assets=assets'
      - uses: actions/upload-artifact@v2
        with:
          name: app
          path: dist/actiontest/windows
        
  build_on_macos:
  
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements and installer
        run: |
          pip install flet requests multitasking retry psutil pyinstaller httpx nuitka
      - name: Run Nuitka
        run: |
          nuitka main.py --standone --onefile --assume-yes-for-downloads --follow-stdlib --show-scons --show-progress --show-memory --include-data-dir='/Config=Config' --include-data-dir='/lib=lib' --include-data-dir='/ui=ui' --include-data-dir='/assets=assets'
      - uses: actions/upload-artifact@v2
        with:
          name: app
          path: dist/actiontest/windows

  build_on_ubuntu:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements and installer
        run: |
          pip install flet requests multitasking retry psutil pyinstaller httpx nuitka
      - name: Run Nuitka
        run: |
          nuitka main.py --standone --onefile --assume-yes-for-downloads --follow-stdlib --show-scons --show-progress --show-memory --include-data-dir='/Config=Config' --include-data-dir='/lib=lib' --include-data-dir='/ui=ui' --include-data-dir='/assets=assets'
      - uses: actions/upload-artifact@v2
        with:
          name: app
          path: dist/actiontest/windows